#!/usr/bin/env python3

import pexpect
import sys


if __name__ == '__main__':
    bctl = pexpect.spawnu('bluetoothctl')
    bctl.logfile = sys.stdout

    # Wait for at least one controller (adapter)
    while True:
        try:
            bctl.expect('Controller [0-9A-F:]+', timeout=5)
            break
        except pexpect.ExceptionPexpect:
            pass

    # Turn on pairing agent
    bctl.sendline('agent on')
    bctl.expect('Agent registered', timeout=1)
    bctl.sendline('default-agent')
    bctl.expect('Default agent request successful', timeout=1)

    # Accept all pairings and PAN requests
    while True:
        try:
            index = bctl.expect(['Confirm passkey', 'Authorize service [0-9a-f-]+'])
            bctl.sendline('yes')
        except pexpect.ExceptionPexpect:
            pass
